import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoryBlokProvider from "@/components/StoryBlokProvider";
import { fetchConfig } from "@/lib/storyblok";
import Header from "@/components/sb/Header";
import Footer from "@/components/sb/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const configStory = await fetchConfig();

  return (
    <StoryBlokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {configStory?.content?.header && (
            <Header blok={configStory.content.header[0]} />
          )}

          <main className="">{children}</main>

          {configStory?.content?.footer && (
            <Footer blok={configStory.content.footer[0]} />
          )}
        </body>
      </html>
    </StoryBlokProvider>
  );
}
